scraper:
  driver:
    url: http://localhost:4444/wd/hub
    headless: false

bucket:
  id: c70b4eb3dec4dd7a89a0081c
  name: webfetcher
  region: us-west-002
  key-id: 0057be3e4da908c0000000002
  key-name: webfetcherkey
  application-key: K005GSWeK/OTB+fiQjJ52syE/Qf13Zo

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/web-fetcher
    username: web-fetcher
    password: s3cr3t
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    out-of-order: true
    schemas: public