apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      restartPolicy: Always
      containers:
        - image: "{{ .Values.image }}:{{ .Values.version }}"
          imagePullPolicy: Always
          name: {{ .Values.app }}
          ports:
            - containerPort: 8080
          env:
            - name: SCRAPER_DRIVER_URL
              value: http://46.36.36.82:4444/wd/hub
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app }}-secrets
                  key: SPRING_DATASOURCE_URL
                  optional: false
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app }}-secrets
                  key: SPRING_DATASOURCE_USERNAME
                  optional: false
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app }}-secrets
                  key: SPRING_DATASOURCE_PASSWORD
                  optional: false
            - name: VCS_REF
              value: {{ .Values.version | quote }}
          livenessProbe:
            # failureThreshold: 10
            initialDelaySeconds: 45
            periodSeconds: 15
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          readinessProbe:
            # failureThreshold: 10
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 12
            httpGet:
              path: /
              port: 8080
              scheme: HTTP